@Api_HostAddress = http://localhost:5202

### Users api's 

### Get all users
GET {{Api_HostAddress}}/api/users
Accept: application/json

### Get user by id
GET {{Api_HostAddress}}/api/users/1
Accept: application/json

### Create user
POST {{Api_HostAddress}}/api/users
Content-Type: application/json

{
  "userName": "jhondoe",
  "email": "john.doe@example.com",
  "password": "11111"
}
### Conversations Api's 

### Get all conversations
GET {{Api_HostAddress}}/api/conversations
Accept: application/json

### Get conversation by id
GET {{Api_HostAddress}}/api/conversations/1
Accept: application/json

### Create conversation
POST {{Api_HostAddress}}/api/conversations
Content-Type: application/json

{
  "name": "General"
}

###
