@baseUrl = http://localhost:5202

### Users api's 

### Get all users
GET {{baseUrl}}/api/users
Accept: application/json

### Get user by id
GET {{baseUrl}}/api/users/1
Accept: application/json

### Create user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "userName": "jhondoe",
  "email": "john.doe@example.com",
  "password": "11111"
}


##################################################
# Conversations API
##################################################

### Get all conversations
GET {{baseUrl}}/api/conversations


### Get conversation by ID
GET {{baseUrl}}/api/conversations/1


### Get conversation that doesn't exist
GET {{baseUrl}}/api/conversations/999


### Create conversation
POST {{baseUrl}}/api/conversations
Content-Type: application/json

{
    "participantIds": [1, 2]
}